package com.splant.smartgarden.daoModel.Entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 


import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "UNIT_WATER_MODEL".
 */
@Entity
public class UnitWaterModel implements java.io.Serializable {

    private String UnitId;
    private String DeviceId;
    private String DeviceName;//设备名称
    private String CreateTime;
    private String UserId;
    private String ClientId;
    private String MapCoord;
    private String Remarks;
    private String PlantId;
    private String PlantName;
    private Integer PlantCount;
    private String PlantTypeId;
    private String PlantTypeName;
    private String AreaId;
    private String AreaName;
    private String PowerEmery;
    private String DeviceType;
    private String GatewayId;//2016.12.23添加
    private String GatewayName;//2016.12.23添加


    public String getGatewayName() {
        return this.GatewayName;
    }
    public void setGatewayName(String GatewayName) {
        this.GatewayName = GatewayName;
    }
    public String getGatewayId() {
        return this.GatewayId;
    }
    public void setGatewayId(String GatewayId) {
        this.GatewayId = GatewayId;
    }
    public String getDeviceType() {
        return this.DeviceType;
    }
    public void setDeviceType(String DeviceType) {
        this.DeviceType = DeviceType;
    }
    public String getPowerEmery() {
        return this.PowerEmery;
    }
    public void setPowerEmery(String PowerEmery) {
        this.PowerEmery = PowerEmery;
    }
    public String getAreaName() {
        return this.AreaName;
    }
    public void setAreaName(String AreaName) {
        this.AreaName = AreaName;
    }
    public String getAreaId() {
        return this.AreaId;
    }
    public void setAreaId(String AreaId) {
        this.AreaId = AreaId;
    }
    public String getPlantTypeName() {
        return this.PlantTypeName;
    }
    public void setPlantTypeName(String PlantTypeName) {
        this.PlantTypeName = PlantTypeName;
    }
    public String getPlantTypeId() {
        return this.PlantTypeId;
    }
    public void setPlantTypeId(String PlantTypeId) {
        this.PlantTypeId = PlantTypeId;
    }
    public Integer getPlantCount() {
        return this.PlantCount;
    }
    public void setPlantCount(Integer PlantCount) {
        this.PlantCount = PlantCount;
    }
    public String getPlantName() {
        return this.PlantName;
    }
    public void setPlantName(String PlantName) {
        this.PlantName = PlantName;
    }
    public String getPlantId() {
        return this.PlantId;
    }
    public void setPlantId(String PlantId) {
        this.PlantId = PlantId;
    }
    public String getRemarks() {
        return this.Remarks;
    }
    public void setRemarks(String Remarks) {
        this.Remarks = Remarks;
    }
    public String getMapCoord() {
        return this.MapCoord;
    }
    public void setMapCoord(String MapCoord) {
        this.MapCoord = MapCoord;
    }
    public String getClientId() {
        return this.ClientId;
    }
    public void setClientId(String ClientId) {
        this.ClientId = ClientId;
    }
    public String getUserId() {
        return this.UserId;
    }
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }
    public String getCreateTime() {
        return this.CreateTime;
    }
    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }
    public String getDeviceName() {
        return this.DeviceName;
    }
    public void setDeviceName(String DeviceName) {
        this.DeviceName = DeviceName;
    }
    public String getDeviceId() {
        return this.DeviceId;
    }
    public void setDeviceId(String DeviceId) {
        this.DeviceId = DeviceId;
    }
    public String getUnitId() {
        return this.UnitId;
    }
    public void setUnitId(String UnitId) {
        this.UnitId = UnitId;
    }

    @Generated(hash = 1940390541)
    public UnitWaterModel(String UnitId, String DeviceId, String DeviceName, String CreateTime,
                          String UserId, String ClientId, String MapCoord, String Remarks, String PlantId,
                          String PlantName, Integer PlantCount, String PlantTypeId, String PlantTypeName,
                          String AreaId, String AreaName, String PowerEmery, String DeviceType, String GatewayId,
                          String GatewayName) {
        this.UnitId = UnitId;
        this.DeviceId = DeviceId;
        this.DeviceName = DeviceName;
        this.CreateTime = CreateTime;
        this.UserId = UserId;
        this.ClientId = ClientId;
        this.MapCoord = MapCoord;
        this.Remarks = Remarks;
        this.PlantId = PlantId;
        this.PlantName = PlantName;
        this.PlantCount = PlantCount;
        this.PlantTypeId = PlantTypeId;
        this.PlantTypeName = PlantTypeName;
        this.AreaId = AreaId;
        this.AreaName = AreaName;
        this.PowerEmery = PowerEmery;
        this.DeviceType = DeviceType;
        this.GatewayId = GatewayId;
        this.GatewayName = GatewayName;
    }

    @Generated(hash = 1282444676)
    public UnitWaterModel() {
    }

    public UnitWaterModel(String UnitId) {
        this.UnitId = UnitId;
    }

}
